// Code generated by "stringer -type=MessageType -linecomment -output=messagetype_string.go"; DO NOT EDIT.
// NOTE: The stringer-generated `func _` compile-time discriminator was
// removed by hand: it is unreachable by name (named `_`) so coverage
// tooling reports it as 0% and trips zenflow's per-function 100% gate.
// The iota-alignment check it provided is preserved by
// TestMessageType_StringerConstants in router_string_test.go, which fails
// loudly if MessageInfo/MessageCancel/MessageContextUpdate/MessageResumeReply
// drift from their expected ordinal values. Re-running `go generate`
// (see //go:generate in router.go) will regenerate the discriminator;
// remove it again after regeneration.

package router

import "strconv"

const _MessageType_name = "infocancelcontext_updateresume_reply"

var _MessageType_index = [...]uint8{0, 4, 10, 24, 36}

func (i MessageType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MessageType_index)-1 {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[idx]:_MessageType_index[idx+1]]
}
