package router

import (
	"context"
	"testing"
)

// fakeResumer is a minimal Resumer for tests in this package.
// (The root package has its own fakeResumer in resume_mechanism_test.go.)
type fakeResumer struct {
	can       bool
	resumeErr error
}

func (f *fakeResumer) CanResume(_ string) bool { return f.can }
func (f *fakeResumer) ResumeStep(_ context.Context, _, _, _ string) (*ResumeHandle, error) {
	return nil, f.resumeErr
}

// TestRouter_Send_ResumerMailboxFullOnResumeEmitsMailboxFull covers
// router.go:594 (the ErrMailboxFullOnResume branch of the resumer
// error switch).
func TestRouter_Send_ResumerMailboxFullOnResumeEmitsMailboxFull(t *testing.T) {
	r := NewRouter()
	r.SetMailbox(NewInMemoryMailboxStore())
	resumer := &fakeResumer{can: true, resumeErr: ErrMailboxFullOnResume}
	r.SetResumer(resumer)

	var drops []DropEvent
	r.SetOnDrop(func(de DropEvent) { drops = append(drops, de) })
	r.RegisterInbox("s")
	r.Close("s")

	_ = r.Send("s", Message{From: "coord", Content: "hi", MessageID: "m"})

	if len(drops) != 1 {
		t.Fatalf("want 1 drop, got %d: %+v", len(drops), drops)
	}
	if drops[0].Reason != DropReasonMailboxFull {
		t.Fatalf("reason=%v want DropReasonMailboxFull", drops[0].Reason)
	}
}

// TestMessageType_String covers every enum case + default for
// MessageType.String (generated by stringer in messagetype_string.go).
// Out-of-range values fall back to the stringer default "MessageType(N)".
func TestMessageType_String(t *testing.T) {
	cases := []struct {
		name string
		in   MessageType
		want string
	}{
		{"info", MessageInfo, "info"},
		{"cancel", MessageCancel, "cancel"},
		{"context_update", MessageContextUpdate, "context_update"},
		{"resume_reply", MessageResumeReply, "resume_reply"},
		{"unknown", MessageType(9999), "MessageType(9999)"},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			if got := c.in.String(); got != c.want {
				t.Errorf("MessageType(%d).String()=%q want %q", c.in, got, c.want)
			}
		})
	}
}

// TestMessageType_StringerConstants preserves the iota-alignment guard
// that the generated `func _` discriminator in messagetype_string.go
// used to provide. We removed that discriminator (see file header
// comment) because it tripped the 100% per-function coverage gate; this
// test is the runtime replacement. It fails loudly if any MessageType
// constant drifts from its expected ordinal value, signalling that
// stringer needs to be re-run.
func TestMessageType_StringerConstants(t *testing.T) {
	cases := []struct {
		name string
		got  MessageType
		want MessageType
	}{
		{"MessageInfo", MessageInfo, 0},
		{"MessageCancel", MessageCancel, 1},
		{"MessageContextUpdate", MessageContextUpdate, 2},
		{"MessageResumeReply", MessageResumeReply, 3},
	}
	for _, c := range cases {
		if c.got != c.want {
			t.Errorf("%s = %d, want %d (re-run `go generate ./internal/router`)", c.name, c.got, c.want)
		}
	}
}

// TestDropReason_String_Phase712 covers the enum values that
// were untouched by earlier tests (router.go:222). Strings come from
// the canonical `dropReasonStrings` map - never redefine literals here.
func TestDropReason_String_Phase712(t *testing.T) {
	subset := []DropReason{
		DropReasonNoTranscript,
		DropReasonTranscriptTooLarge,
		DropReasonResumeShutdown,
		DropReasonResolverError,
		DropReasonUnspecified,
	}
	for _, in := range subset {
		in := in
		want, ok := dropReasonStrings[in]
		if !ok {
			t.Fatalf("dropReasonStrings missing %v - canonical map drifted from enum", in)
		}
		t.Run(want, func(t *testing.T) {
			if got := in.String(); got != want {
				t.Errorf("DropReason(%d).String()=%q want %q", in, got, want)
			}
		})
	}
}
